"""Runtime session loop and modular-robot metrics."""

from modsim.runtime.inspection import (
    RuntimeEventRow,
    RuntimeInspectionError,
    RuntimeInspectorFrame,
    RuntimeScenarioStatus,
    build_runtime_inspector_frame,
    event_row,
    format_event_detail,
)
from modsim.runtime.inspection_protocol import (
    MAX_RUNTIME_MESSAGE_BYTES,
    RUNTIME_PROTOCOL_PREFIX,
    RUNTIME_PROTOCOL_VERSION,
    RuntimeError,
    RuntimeFinished,
    RuntimeFinishedReason,
    RuntimeFrame,
    RuntimeHello,
    RuntimeInitialize,
    RuntimeProtocolError,
    RuntimeProtocolFramer,
    RuntimeProtocolMessage,
    RuntimeStatus,
    RuntimeStop,
    decode_runtime_message,
    encode_runtime_message,
)
from modsim.runtime.inspector_runner import (
    RuntimeInspectorConfig,
    RuntimeInspectorRunner,
    RuntimeInspectorSetupError,
    resolve_runtime_connector_pair,
    resolve_runtime_module_type,
    resolve_runtime_recipe,
    runtime_frame_signature,
    validate_runtime_inspector_config,
)
from modsim.runtime.metrics import DockingMetrics, collect_metrics
from modsim.runtime.presets import (
    SMORES_DRIVER_TO_SNAKE_SOURCE,
    RuntimeDemo,
    smores_driver_to_snake_plan,
)
from modsim.runtime.reconfiguration import (
    AssemblyDockingSetup,
    ConnectorPairRef,
    ReconfigurationAction,
    ReconfigurationPhase,
    ReconfigurationPlan,
    ReconfigurationPlanError,
    ReconfigurationScenarioError,
    ReconfigurationStatus,
    ScriptedReconfigurationConfig,
    ScriptedReconfigurationScenario,
    stage_docking_assembly_pair,
)
from modsim.runtime.scenarios import (
    DockingPairPhase,
    DockingPairScenario,
    DockingPairScenarioConfig,
    DockingPairScenarioStatus,
    DockingPairSetup,
    ScenarioSetupError,
    stage_docking_pair,
)
from modsim.runtime.session import RuntimeSession

__all__ = [
    "MAX_RUNTIME_MESSAGE_BYTES",
    "RUNTIME_PROTOCOL_PREFIX",
    "RUNTIME_PROTOCOL_VERSION",
    "SMORES_DRIVER_TO_SNAKE_SOURCE",
    "AssemblyDockingSetup",
    "ConnectorPairRef",
    "DockingMetrics",
    "DockingPairPhase",
    "DockingPairScenario",
    "DockingPairScenarioConfig",
    "DockingPairScenarioStatus",
    "DockingPairSetup",
    "ReconfigurationAction",
    "ReconfigurationPhase",
    "ReconfigurationPlan",
    "ReconfigurationPlanError",
    "ReconfigurationScenarioError",
    "ReconfigurationStatus",
    "RuntimeDemo",
    "RuntimeError",
    "RuntimeEventRow",
    "RuntimeFinished",
    "RuntimeFinishedReason",
    "RuntimeFrame",
    "RuntimeHello",
    "RuntimeInitialize",
    "RuntimeInspectionError",
    "RuntimeInspectorConfig",
    "RuntimeInspectorFrame",
    "RuntimeInspectorRunner",
    "RuntimeInspectorSetupError",
    "RuntimeProtocolError",
    "RuntimeProtocolFramer",
    "RuntimeProtocolMessage",
    "RuntimeScenarioStatus",
    "RuntimeSession",
    "RuntimeStatus",
    "RuntimeStop",
    "ScenarioSetupError",
    "ScriptedReconfigurationConfig",
    "ScriptedReconfigurationScenario",
    "build_runtime_inspector_frame",
    "collect_metrics",
    "decode_runtime_message",
    "encode_runtime_message",
    "event_row",
    "format_event_detail",
    "resolve_runtime_connector_pair",
    "resolve_runtime_module_type",
    "resolve_runtime_recipe",
    "runtime_frame_signature",
    "smores_driver_to_snake_plan",
    "stage_docking_assembly_pair",
    "stage_docking_pair",
    "validate_runtime_inspector_config",
]
